[hololens]
container = "ghcr.io/hologit/lenses/mkdocs:latest"

[hololens.mkdocs]
requirements = [
    "mkdocs-material",
    "mkdocs-awesome-pages-plugin",
    "mdx_truly_sane_lists"
]

[hololens.output]
merge = "replace"
