name: Publish Actions to develop stream

on:
  push:
    branches: [develop]


jobs:
  publish-actions-develop:
    runs-on: ubuntu-latest
    steps:
    - name: 'Update holobranch: actions/projector/develop'
      uses: ./github-actions/projector/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ref: develop
        holobranch: github-action-projector
        commit-to: actions/projector/develop
